### ISSUE TITLE
Find and Transform creating errors

### ISSUE THREAD

**Issue by Zxynine** [ArturoDent/find-and-transform#10]
Recently I had noticed my shortcuts were no longer working, I tried a number of things but nothing worked, finally I tried to run a command from this extension and all of them return errors: 
![image](https://user-images.githubusercontent.com/79198508/207413198-3a8d608a-f482-48d0-b681-be59a2359efd.png)
![image](https://user-images.githubusercontent.com/79198508/207413382-2ba0af05-5943-408e-9bb3-0570848875c2.png)
![image](https://user-images.githubusercontent.com/79198508/207413646-b6eb5e79-ea4c-4557-b737-8aa298ac1a50.png)

I have tested on another computer and was getting errors as well. Most of them were the same as the first screenshot, however on this computer after opening a folder for the workspace, things seem to be working. Its odd though as on the other computer I had already had a workspace folder open and was receiving errors. You may want to add a few checks catching and handling these edge cases, as vscode error messages are utterly worthless as im sure youre aware.

**Comment by ArturoDent** [comment]
Were the errors only when you were using the `Search in this File/Folder` commands?  From an editor context menu or from the Explorer context menu?

Do you have an example of a keybinding that is producing an error still?

There are a few issues on GH about searching within absolute paths and non-existent workspaces but they give a different error.  Still I see there is something I may be able to when searching in files not in a workspace - maybe.

**Comment by Zxynine** [comment]
> Were the errors only when you were using the `Search in this File/Folder` commands? From an editor context menu or from the Explorer context menu?
> 
> Do you have an example of a keybinding that is producing an error still?
> 
> There are a few issues on GH about searching within absolute paths and non-existent workspaces but they give a different error. Still I see there is something I may be able to do when searching in files not in a workspace - maybe.

I made the post from my work computer which seemingly had it fixed after opening the workspace folder (I dont often shut down my home comp so I thought that that was part of the problem), however, testing it at home now I had my computer shut down and update last night so I am testing on a freshly opened vscode and I am still having problems.

Just tested Search in this file:
![image](https://user-images.githubusercontent.com/79198508/207739123-0e763f6a-d5b9-491f-a643-26de603b0a3f.png)
![image](https://user-images.githubusercontent.com/79198508/207739385-018ee9ef-f7ab-478b-9700-34ab9acc145f.png)

None of my keybinds work on my computer either, I have a feeling that whatever error is going on with the extension is causing it to entirely fail working. My keybindings do not produce any errors, they just simply dont work. They did however work on the other computer after a little bit. I have not changed my keybindings before the problems occurred so I dont think it is their fault, but i will conclude them for the sake of completion
![image](https://user-images.githubusercontent.com/79198508/207739749-e530246a-5d80-4981-983f-9d28521fa136.png)

I was running the commands to test to see if your extension was working by opening the command pallet "ctrl+shift+p" and searching for them, im not sure how/what you are referring to by the editor context menu. 

Personally I dont care if you fix not being able to search when not in a workspace, I didnt even realise that was a problem, my suggestion is to just add an error message so that vscode does not try and sort it out as anything you put there would be more informative than vscodes messages lol.

**Comment by Zxynine** [comment]
I can confirm, testing it out on the computer at my work, the extension seems to work fine, but at home it is producing errors. Have any idea what can cause this to happen?

**Comment by ArturoDent** [comment]
Are you in a workspace in both places?

Also, some people, including me, are having big problems with vscode v1.74.  I can't even use the Stable Build but the Insiders version is fine.  And it has something to do with loading extensions.  It is a little odd that no one else has reported problems with this extension lately. 

I could ask you to downgrade your home version vscode to v1.73 and see if that improves things (or try the Insiders version) but we could just wait a bit to see if v1.74 gets fixed.  And I'll work on detecting the absence of a workspace (which is problematic for vscode searches and has long-standing issues on github) and see if that helps.

Thanks for all your effort.

**Comment by Zxynine** [comment]
> Are you in a workspace in both places? And are both your computers on vscode v1.74+?
> 
> Also, some people, including me, are having big problems with vscode v1.74. I can't even use the Stable Build but the Insiders version is fine. And it has something to do with loading extensions. It is a little odd that no one else has reported problems with this extension lately.
> 
> I could ask you to downgrade your home version vscode to v1.73 and see if that improves things (or try the Insiders version) but we could just wait a bit to see if v1.74 gets fixed. And I'll work on detecting the absence of a workspace (which is problematic for vscode searches and has long-standing issues on github) and see if that helps.
> 
> Thanks for all your effort.

Hey, sorry its been a while, been terribly busy. For a long time I was having the problem of it not working, tried every once in a while when I was desperate to have my shortcut for converting code styles. I never tried to downgrade vscode because vscode does not make it easy and im low on storage space. I just tried it once more and to my surprise it works just fine now! Whatever changes you made in the recent update seems to have fixed whatever weird problems I was having.

**Comment by Zxynine** [comment]
It may have been an update prior to this, I don't try often enough to know for sure, but it was one of the last semi recent updates.
