### ISSUE TITLE
e.replace is not a function

### ISSUE THREAD

**Issue by BlueAndi** [ArturoDent/find-and-transform#12]
VSCode: 1.75.1
Find-and-Transform: v4.4.5

```json
{
    "key": "alt+r",
    "command": "findInCurrentFile",
    "args": {
        "find": "(.* /\\* )([0-9]+)(.*)",
        "replace": "$${ console.log(\"Hello World!\"); return $2 }$$",
        "isRegex": true
    }
}
```

Result in debug console:

![image](https://user-images.githubusercontent.com/9699465/220931631-cd6a6dc9-364d-4c83-b1d7-e123e1bdd5e0.png)

**Comment by ArturoDent** [comment]
Hello,  What is the text you are trying to match?  That will help me.  Thanks.

**Comment by BlueAndi** [comment]
To reproduce it, I used this dummy text:
```txt
0
1
abc /* 2 test */
3
4

```

**Comment by ArturoDent** [comment]
I am having difficulty replicating the issue within this extension.  I see from your stack trace that it is erroring in a python extension.  There is no `replace()` call at line 291 in the `resolveVariables.js` file so I think the problem may be elsewhere.

If you want the `console.log....` printed out you should be using this form of the replace:

`"replace": "$${ return `console.log(\"Hello World!\") $2` }$$",`

So everything that you want to be used as the replacement must be `return`ed.  Here is a demo using this keybinding:

```jsonc
{
  "key": "alt+r",
  "command": "findInCurrentFile",
  "args": {
     "find": "(.* /\\* )([0-9]+)(.*)",
    "replace": "$${ return `console.log(\"Hello World!\") $2` }$$",
    "isRegex": true
  }
}
```

![demoOf Transform](https://user-images.githubusercontent.com/31813701/221304008-0852668c-ed79-4522-8d51-4787b1418d2a.gif)

Is that the result you are looking for?

**Comment by BlueAndi** [comment]
> I am having difficulty replicating the issue within this extension. I see from your stack trace that it is erroring in a python extension. There is no `replace()` call at line 291 in the `resolveVariables.js` file so I think the problem may be elsewhere.

Because of your hint, I figured out that the problem appears if the following extension is active:
https://marketplace.visualstudio.com/items?itemName=ms-python.python

After disabling the extension and a reload, find-and-transform is replacing as expected.

Note, the console.log() is only there for debugging purposes. I wanted to see the log on the console.

Thanks for your analysis! Its really a great very helpfull extension!
