### ISSUE TITLE
CURRENT_TIMEZONE_OFFSET?

### ISSUE THREAD

**Issue by mitechzone** [ArturoDent/find-and-transform#13]
Thanks for creating this extension.

Is it possible to add [CURRENT_TIMEZONE_OFFSET](https://github.com/microsoft/vscode/pull/170518) as a variable?

I'm trying to come up with a cleaner solution to insert current datetime in this format:

> 2023-02-24T03:52:55-08:00

At the moment, the code is quite complex:

```"replace": "${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE}T${CURRENT_HOUR}:${CURRENT_MINUTE}:${CURRENT_SECOND}$${ var offset = new Date().getTimezoneOffset(), o = Math.abs(offset); return (offset < 0 ? \"+\" : \"-\") + (\"00\" + Math.floor(o / 60)).slice(-2) + \":\" + (\"00\" + (o % 60)).slice(-2); }$$"```

**Comment by ArturoDent** [comment]
Would it only involve implementing this code from the PR:

```js
} else if (name === 'CURRENT_TIMEZONE_OFFSET') {
    const rawTimeOffset = this._date.getTimezoneOffset();
    const sign = rawTimeOffset < 0 ? '-' : '+';
    const sign = rawTimeOffset > 0 ? '-' : '+';
    const hours = Math.trunc(Math.abs(rawTimeOffset / 60));
    const hoursString = (hours < 10 ? '0' + hours : hours);
    const minutes = Math.abs(rawTimeOffset) - hours * 60;
    const minutesString = (minutes < 10 ? '0' + minutes : minutes);
    return sign + hoursString + ':' + minutesString;
}
```

**Comment by mitechzone** [comment]
I would think so. Although there is one small issue:

```javascript
    const sign = rawTimeOffset < 0 ? '-' : '+';  // I don't see this line in the PR.
    const sign = rawTimeOffset > 0 ? '-' : '+';  // This line looks right.
```

**Comment by ArturoDent** [comment]
Sorry, I was looking at the diff of a later fix (and of course the copy/paste doesn't show that).  They deleted the first `sign` and changed it to what you indicated was correct: `const sign = rawTimeOffset > 0 ? '-' : '+';`

----------------

On second thought, I see this from

[Negative values and positive values](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset#negative_values_and_positive_values)

> The number of minutes returned by `getTimezoneOffset()` is positive if the local time zone is behind UTC, and negative if the local time zone is ahead of UTC. For example, for UTC+10, -600 will be returned.

Where I live, Albuquerque, New Mexico, we are 7 hours behind UTC, or `UTC-7 hours`.  According to the above quote, the timeZoneOffset should be reported as a positive number.   

But `const sign = rawTimeOffset > 0 ? '-' : '+';` would present that as `-07:00`. That doesn't seem right to me, what is the norm for reporting the offset when the locale is behind UTC?  DO you want to see a positive or negative number?

**Comment by ArturoDent** [comment]
With this keybinding:

```jsonc
{
  "key": "alt+r",
  "command": "findInCurrentFile",
  "args": {
    "replace": "${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE}T${CURRENT_HOUR}:${CURRENT_MINUTE}:${CURRENT_SECOND}${CURRENT_TIMEZONE_OFFSET}"
  }
}
```

here is the output for Albuquerque, UTC-7:
![timeZoneOffset](https://user-images.githubusercontent.com/31813701/221333403-c0fb1e00-9d25-4865-9ef6-bf6f91d936c5.gif)

I just need to know which sign is correct?

**Comment by mitechzone** [comment]
If it is UTC-7, the output should be `-07:00`. Basically, the sign should match the sign in the UTC notation.

Using C# to verify:

```c#
Console.WriteLine(DateTime.Now.ToString("yyyy-MM-ddTHH:mm:sszzzz"));
```
The output for UTC-7 was `2023-02-25T01:40:20-07:00`.

Similarly, in Sydney Australia (UTC+11), the output from .NET was `2023-02-25T19:41:32+11:00`.

**Comment by ArturoDent** [comment]
I've updated the extension to v4.5.0 to include the variable which can be used as:

```plaintext
$CURRENT_TIMEZONE_OFFSET     or
${CURRENT_TIMEZONE_OFFSET}   or
${ CURRENT_TIMEZONE_OFFSET }
```

Please test.  Thank you.

**Comment by mitechzone** [comment]
Thank you! Worked like a charm.
