### ISSUE TITLE
How to insert match groups into `"run"`? Unexpected behavior.

### ISSUE THREAD

**Issue by lukstafi** [ArturoDent/find-and-transform#14]
The following code does not work, but removing `"run"` and uncommenting `"replace"` makes things work (in a bit of a roundabout way).
```
{
    "key": "alt+q",
    "command": "findInCurrentFile",
    "args": {
      "description": "Open file at cursor",
      "find": "\"([^\"]+)\":([0-9]+)",
      "run": [
        "$${",
        "vscode.commands.executeCommand('workbench.action.quickOpen', `$1:$2`);",
        "}$$",
      ],
      // "replace": [
      //   "$${",
      //   "vscode.commands.executeCommand('workbench.action.quickOpen', `$1:$2`);",
      //   "return '\\\"$1\\\":$2';",
      //   "}$$",
      // ],
      "isRegex": true,
      "restrictFind": "line",
    }
  }
```

**Comment by ArturoDent** [comment]
Can you give me an example of the file name (and line number) you are testing this on?

**Comment by ArturoDent** [comment]
I have it working, will release soon.  Did you want to open the QuickOpen panel or just open the file directly (with no QuickOpen file showing)?

BTW, there is this caveat currently (from the README):

> As of v4.2.0, `args.run` will only run once with `"restrictFind": "line"`, NOT once for each line.

I think I will work on this so that your line could be `"test1.txt":40  blahblah "test2.js":3` and it would open both - obviously without involving the Quickopen panel.

**Comment by lukstafi** [comment]
Thank you! No worries about working on my specific use-case, it's just the
"replace" route is suboptimal because it marks the editor as modified. I
originally wanted to open the file directly, but I think QuickOpen is
better because I don't have the full paths to the files, just the file name.

**Comment by lukstafi** [comment]
I would be nice to skip showing the `QuickOpen` window but it's not important for me. In my use-case, there will just be one file name in a line -- it's for analyzing debug logs.

**Comment by ArturoDent** [comment]
It took a little longer than I expected, handling backslashes when they go through multiple steps is a real pain.  v4.6.0 should work as you expect now with this:

```jsonc
{
  "key": "alt+q",
  "command": "findInCurrentFile",
  "args": {
    "description": "Open file at cursor",
    "find": "\"([^\"]+)\":([0-9]+)",

    "run": [
      "$${",  
        "await vscode.commands.executeCommand('workbench.action.quickOpen', `$1:$2`);",
      "}$$",
    ],

    "isRegex": true,
    "restrictFind": "line",

    "postCommands": "workbench.action.acceptSelectedQuickOpenItem"
  }
}
```

It now handles these relative path versions:

```plaintext
"test1.txt":4

"src\folder\folder.json":3

"src\\folder\\folder.json":23
```

Here is code to open the file directly, without going through a quickOpen box:

```jsonc
"run": [
  "$${",
    "const pos = new vscode.Position($2, 0);",
    "const range = new vscode.Range(pos, pos);",
    "const options = {selection: range};",
    "const wsFolderUri = vscode.workspace.workspaceFolders[0].uri;",
    "const uri = await vscode.Uri.joinPath(wsFolderUri, '$1');",
    "await vscode.commands.executeCommand('vscode.open', uri, options);",
    
    // "await vscode.commands.executeCommand('workbench.action.quickOpen', `$1:$2`);",
  "}$$",
],
```

It only works for a single root workspace - it only checks `workspaceFolders[0]` - but that could be modified to check all workspaceFolders if necessary.

Let me know if v4.6.0 works for you.
