### ISSUE TITLE
findInCurrentFile not working with version 4.7 and VSCode 1.78.2

### ISSUE THREAD

**Issue by Mr-Hazem-Eng-Artist** [ArturoDent/find-and-transform#17]
I have VSCode v. 1.78.2 (System Installer) & Find and Transform 4.7 . The find & replace is Not working for me with Regex, did I wrongfuly write the Regex ? or there is another issue with those versions I got now ? I also have WIndows 11 22H2,  I am using a standalone keybinding in the keybindings.json as follows:

`{
"key": "ctrl+alt+z",
    "command": "findInCurrentFile",
    "args": {
      "find": [
        "(/Default/Shaders).*(\"\/)",
        "(/Default/Render-Settings\/).*(\"\/)",
        "\n.*(3Delight)(.|\n)+?(<\/Asset>)"
      ],
      "replace": [
        "/Default/Presets/Shader\"\/",
        "/Default/Presets/Render\"\/",
        ""
      ],
      "isRegex": true
    }
  }`

This is a sample of the code I am modifying below, it should find & replace 2 or more results, But for me , It doesn't find anything at all !:

`<Assets>
    <Asset VALUE="Props/Starship Astra/Astra.duf">
     <ContentType VALUE="Prop"/>
     <Audience VALUE="Children"/>
     <Categories>
      <Category VALUE="/Default/Render-Settings"/>
     </Categories>
     <CompatibilityBase VALUE="/Starship Astra/Astra"/>
    </Asset>
    <Asset VALUE="Props/Starship Astra/Astra.duf">
     <ContentType VALUE="Prop"/>
     <Audience VALUE="Children"/>
     <Categories>
      <Category VALUE="/Default/Transportation/Space"/>
     </Categories>
     <CompatibilityBase VALUE="/Starship Astra/Astra"/>
    </Asset>
    <Asset VALUE="Props/Starship Astra/Containers1.duf">
     <ContentType VALUE="Prop"/>
     <Audience VALUE="Children"/>
     <Categories>
      <Category VALUE="/Default/Props/Other"/>
     </Categories>
     <CompatibilityBase VALUE="/Starship Astra/Containers1"/>
    </Asset>
    <Asset VALUE="Props/Starship Astra/Containers2.duf">
     <ContentType VALUE="Prop"/>
     <Audience VALUE="Children"/>
     <Categories>
      <Category VALUE="/Default/Props/Other"/>
     </Categories>
     <CompatibilityBase VALUE="/Starship Astra/Containers2"/>
    </Asset>
    <Asset VALUE="Props/Starship Astra/Materials/3DeLight/Gray.duf">
     <ContentType VALUE="Preset/Materials"/>
     <Audience VALUE="Children"/>
     <Categories>
      <Category VALUE="/Default/Shaders/Vehicles"/>
     </Categories>
     <Compatibilities>
      <Compatibility VALUE="/Starship Astra/Astra"/>
     </Compatibilities>
    </Asset>`

Also, same problem with the "runInSearchPanel" It doesn't work in Bulk Search for multiple files.

**Comment by ArturoDent** [comment]
* Note that I tested this on formatted xml.  What you showed above is probably missing newlines which will affect your third `find`.  But I formatted it like this for testing:

```xml
<Assets>
  <Asset VALUE="Props/Starship Astra/Astra.duf">
    <ContentType VALUE="Prop"/>
    <Audience VALUE="Children"/>
    <Categories>
      <Category VALUE="/Default/Render-Settings"/>
    </Categories>
    <CompatibilityBase VALUE="/Starship Astra/Astra"/>
  </Asset>
  <Asset VALUE="Props/Starship Astra/Astra.duf">
    <ContentType VALUE="Prop"/>
    <Audience VALUE="Children"/>
    <Categories>
      <Category VALUE="/Default/Transportation/Space"/>
    </Categories>
    <CompatibilityBase VALUE="/Starship Astra/Astra"/>
  </Asset>
  <Asset VALUE="Props/Starship Astra/Containers1.duf">
    <ContentType VALUE="Prop"/>
    <Audience VALUE="Children"/>
    <Categories>
      <Category VALUE="/Default/Props/Other"/>
    </Categories>
    <CompatibilityBase VALUE="/Starship Astra/Containers1"/>
  </Asset>
  <Asset VALUE="Props/Starship Astra/Containers2.duf">
    <ContentType VALUE="Prop"/>
    <Audience VALUE="Children"/>
    <Categories>
      <Category VALUE="/Default/Props/Other"/>
    </Categories>
    <CompatibilityBase VALUE="/Starship Astra/Containers2"/>
  </Asset>
  <Asset VALUE="Props/Starship Astra/Materials/3DeLight/Gray.duf">
    <ContentType VALUE="Preset/Materials"/>
    <Audience VALUE="Children"/>
    <Categories>
      <Category VALUE="/Default/Shaders/Vehicles"/>
    </Categories>
    <Compatibilities>
      <Compatibility VALUE="/Starship Astra/Astra"/>
    </Compatibilities>
  </Asset>
</Assets>
```

This keybinding works for me:

```jsonc
{
  "key": "ctrl+alt+z",
  "command": "findInCurrentFile",
  "args": {
    "find": [
      "(/Default/Shaders).*(\"\/)",  // also within your third find which gets deleted later
      
      "(/Default/Render-Settings).*(\"\/)",      
      // "(/Default/Render-Settings\/).*(\"\/)", // has an extra \/ after Render-Settings
      
      // "\n.*(3Delight)(.|\n)+?(<\/Asset>)" - L is not capitalized, but the regex is case-insensitive unless you change that
      "\n.*(3DeLight)(.|\n)+?(<\/Asset>)"
    ],
    "replace": [
      "/Default/Presets/Shader\"\/",
      "/Default/Presets/Render\"\/",
      ""
    ],
    "isRegex": true,
  }
},
```

Note the second `find` won't work as there is an extra `\/` in it which won't match anything.  But the other two `find/replaces` still work.

Note the first `find` - at least for the sample you provided - will be in the third `find` which gets deleted, i.e., replaced with the empty string.

In the third `find` the `l` of `3Delight` is not capitalized.  This doesn't actually matter since the default is case-insensitive.

**Comment by ArturoDent** [comment]
You mentioned that it doesn't work across files.  It does for me with the corrected second `find` above.

But don't expect it to run three consecutive find and replaces across multiple files.  This is from the `searchInPanel.md`:

> There is really no point in having multiple `replaces` as there is no api for stopping the process to wait for the first search and replace to finish before going on to the next.  Therefore, use as many `find`'s as you want and **only one replace** - which will be used for that final search and replace.  Use `${resultsFiles}` to progressively narrrow down the searches to those files with the previous `find`'s.  Likewise, you only need one `"filesToInclude": "${resultsFiles}"` to accomplish this.

There is, at present, no extension api that makes it possible to do multiple find/replaces across files as vscode requires that the user respond to a modal dialog for each replace.  There is a promising experimental api in development that might enable that functionality.

**Comment by Mr-Hazem-Eng-Artist** [comment]
OK thanks for your testing of that case, now I have a better idea of how things are going.  I will wait for that promising future api as I also I really wanted that feature to do multiple find/replace across many files (Bulk multiple find/replace) as I had 24 files formated in xml & each of them needed multiple find/replace (they were 10 replacements , not only three like in my example) & I had to do all of them one by one by hand.
You can Close that issue if you want unless you wanna tell me some extra tips :)
