### ISSUE TITLE
Allow configuration of commands in .code-workspace file and project settings file

### ISSUE THREAD

**Issue by Christian-Marx** [ArturoDent/find-and-transform#18]
First of all, thank you for this great extension!

Currently, new commands can be defined in the user settings file (settings.json), but not in a project settings.json file or in a .code-workspace file. I think the `scope` property of the `findInCurrentFile` object in *package.json* is responsible for that constraint. I tried to change it from `machine` to `machine-overridable` which removed that limitation while everything still seemed to work. Are there any downsides to that approach? If not, could you incorporate the necessary changes?

https://github.com/ArturoDent/find-and-transform/blob/a780991fd04287d9d753270ac090ec52bdabd961/package.json#L110

**Comment by ArturoDent** [comment]
This is a good suggestion.  My testing shows no problems, although it is a little ugly if the same command with a long title appears in both the User and Workspace settings but they both work as expected.

I am working on a couple of other changes so I'll make this `scope` change soon.

Thanks.

**Comment by Christian-Marx** [comment]
That's great, thanks!

**Comment by ArturoDent** [comment]
v4.7.1 is out with the change.  Let me know if it works as you wanted.  Thanks.

**Comment by Christian-Marx** [comment]
Thanks, works like a charm.
