### ISSUE TITLE
Regex Find/Replace ends with multiple selections and cursors

### ISSUE THREAD

**Issue by mlao-pdx** [ArturoDent/find-and-transform#19]
Thank you for this great extension. However, I must be doing something wrong.

I'm trying to add two trailing spaces to line breaks in Markdown files automatically when saving.

## .vscode/settings.json:
```json
...

  "findInCurrentFile": {
    "DoubleSpaceLineBreaks": {
      "find": "(?<=[.!?\"])[\\r\\t\\f\\v ]*\\n(?![\\r\\t\\f\\v ]*\\n|$)",
      "isRegex": true,
      "replace": "  \n",
      "title": "Double space line breaks"
    }
  },

...

  "[markdown]": {
    "editor.codeActionsOnSave": {
      "source.DoubleSpaceLineBreaks": true,
      "source.fixAll.markdownlint": true
    }
  },

...
```
## Markdown
```markdown
# Test title

We want two spaces at the end of this.  
No change in spaces at the end of this.

Then two spaces at the end of this.  
And no change in spaces at teh end of this.

`print("No spaces at the end of this.")`

But do not add spaces to the end of this.

```
The Find/Replace works fine in the editor, but when saving to run Find-and-Transform, both lines are properly changed , yet have their trailing spaces selected and there are now two cursors.

<img width="478" alt="image" src="https://github.com/ArturoDent/find-and-transform/assets/21014310/5469602d-e3b1-47c8-b60a-0ff07cbe267d">

How can I get the editor's behavior, instead? Cursor location has not changed/multiplied, but lines were updated.

**Comment by ArturoDent** [comment]
If I understand correctly you can add a 

```jsonc
"postCommands": "cancelSelection"
```

to the `"DoubleSpaceLineBreaks"` setting (just after your title) and it should get rid of the selections and leave just one cursor.

**Comment by mlao-pdx** [comment]
Thank you for the quick reply.

> ```js
> "postCommands": "cancelSelection"
> ```

Almost there... I toyed with `postCommands`, but not the right ones... This does release the selections, which was my biggest hurdle. Is there any way to restore the original cursor position? 

Also, do you have a donation option to show my appreciation?

**Comment by mlao-pdx** [comment]
Here's what I've come up with, so far. While it runs the risk of leaving breadcrumbs, it does not seem likely. I assume edge cases such as BOF/EOF and such might cause issues. Good enough for my needs:

## setting.json
```json
...

  "findInCurrentFile": {
    "MarkCursorLocation": {
      "find": "(\\$1)",
      "isRegex": true,
      "postCommands": "cancelSelection",
      "replace": "$1e1bcfb09-0078-4c36-8e0d-fdf14b8286d7",
      "title": "Mark cursor location (UUID4)",
      "restrictFind": "onceIncludeCurrentWord"
    },
    "RestoreCursorLocation": {
      "find": "e1bcfb09-0078-4c36-8e0d-fdf14b8286d7",
      "postCommands": "cancelSelection",
      "replace": "",
      "title": "Restore cursor location (UUID4)"
    },
    "DoubleSpaceLineBreaks": {
      "find": "(?<=[.!?\"])[\\r\\t\\f\\v ]*\\n(?![\\r\\t\\f\\v ]*\\n|$)",
      "isRegex": true,
      "postCommands": "cancelSelection",
      "replace": "  \n",
      "title": "Double space line breaks"
    }
  },

...

  "[markdown]": {
    "editor.codeActionsOnSave": {
      "source.MarkCursorLocation": true,
      "source.DoubleSpaceLineBreaks": true,
      "source.RestoreCursorLocation": true,
      "source.fixAll.markdownlint": true
    }
  },

...
```

**Comment by ArturoDent** [comment]
I am going to re-open.  I think I can give you the option to restore cursors/selections with an option.  So you don't have to jump through those hoops.  There are a lot of interesting things you can do with the find's if they are selected, so that explains the decision to select all those (for example, you can loop through those selections in a replace/run and act on each one or aggregate them, etc.

But it looks like I can introduce another option to `preserveSelections` because in cases like yours you do not the finds to be selected.

**Comment by mlao-pdx** [comment]
> I am going to re-open. 

Works for me. Your call, I didn't think me leaving it open was fair, as my problem was not truly a bug.

> I think I can give you the option to restore cursors/selections with an option. So you don't have to jump through those hoops.
> But it looks like I can introduce another option to `preserveSelections` because in cases like yours you do not the finds to be selected.

Agreed. I have been updating my solution above with tweaks to address edge cases. Now the UUID placeholder is all over the regex to avoid tripping over it. Furthermore, having things broken up into three commands, makes Undo/Redo clunky after a Save.

That's the thing I keep forgetting: I know it is three commands when setting it up, but when in the flow of writing the extra undos keep surprising me.

> There are a lot of interesting things you can do with the find's if they are selected, so that explains the decision to select all those (for example, you can loop through those selections in a replace/run and act on each one or aggregate them, etc.

Yes, I have started to see opportunities. Yet, I do want to make sure that I know what I'm doing, and not make Find-and-Transform my latest "hammer". ;)

**Comment by ArturoDent** [comment]
I just published v4.8.0 which I think simplifies your case.  You can use the new argument

```json
"preserveSelections": true
```

and your preexisting cursor positions and selections shouldn't be changed.  Let me know if it works for you.  Thanks.

**Comment by mlao-pdx** [comment]
> I just published v4.8.0

Looks like Marketplace still considers v4.7.2 the latest and greatest. Is there another way I should install v4.8.0?

**Comment by ArturoDent** [comment]
It just a few minutes.  You can also click on the extension in the Extensions view and then click on the down arrow next to `Uninstall`, choose `Install Another Version` and it'll be there.

**Comment by mlao-pdx** [comment]
> choose `Install Another Version`

Learned something new. 

```json
"preserveSelections": true
```

@ArturoDent: This works flawlessly. Thank you so much for the extra feature and responsiveness. It also makes the Undo/Redo work as expected: The Find/Replace is one single Undo, and I'm back at "my own" edits. Very smooth.

**Comment by ArturoDent** [comment]
Great, thanks for filing an issue and testing the extension.

I did create a "Buy me a cup of coffee" account: [Arturo likes coffee](https://www.buymeacoffee.com/ArturoDent).  Thank you.

**Comment by mlao-pdx** [comment]
> Great, thanks for filing an issue and testing the extension.
> 
> I did create a "Buy me a cup of coffee" account: [Arturo likes coffee](https://www.buymeacoffee.com/ArturoDent). Thank you.

You shall be sufficiently caffeinated. ;)

**Comment by mlao-pdx** [comment]
For those folks wondering why the preserveSelections is a nice option, here is another use I found. When you find yourself toggling todo's in markdown, you could add this to your keybindings:

```json
  {
    "args": {
      "find": "(-\\s+\\[)( )?(x)?(\\].*?)(?=\\n|-->)",
      "isRegex": true,
      "preserveSelections": true,
      "replace": "$1${2:?x:}${3:? :}$4",
      "restrictFind": "matchAroundCursor"
    },
    "command": "findInCurrentFile",
    "key": "alt+x",
    "when": "editorTextFocus && editorLangId == markdown"
  }
```
