### ISSUE TITLE
CPU goes UP after few times searchin in project

### ISSUE THREAD

**Issue by gs** [ArturoDent/find-and-transform#2]
- Issue Type: `Bug`
- Extension Name: `find-and-transform`
- Extension Version: `0.9.81`
- OS Version: `Darwin x64 20.6.0`
- VS Code version: `1.63.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

After executing few times the extension and searching inside the project, I see that the my CPU goes UP because of `fzf` + `rg` ? Is that something that is related to the extension or not? As I see that happening only when extension is active.

**Comment by ArturoDent** [comment]
I assume you are you doing a `runInSearchPanel ` command?  Can you show the keybinding or setting that you are using.   Does this happen when you restrict the search to a smaller set of files?


`fzf` + `rg` are related to ripgref the search package used in vscode.  The  `runInSearchPanel ` uses vscode's search in files functionality, just passing some resolved variables to its usual arguments.

**Comment by ArturoDent** [comment]
Closing as it needs more information as requested.
