### ISSUE TITLE
use javascript in “find” field  

### ISSUE THREAD

**Issue by Haale** [ArturoDent/find-and-transform#20]
Is it possible to use javascript in "find" filed? 
For example, read a regular expression string from a text file and convert the raw string to the format string (like transforming backslash into double backslash,double quote into backslash+double quote) that javascript accepts.

Or have  the "Find and Transform" supported that feature already?

**Comment by ArturoDent** [comment]
How do you want to use this exactly? In general, you can not use javascript to create a `find` query from code selected in a file (although that is an interesting idea), but you can use regex's in text as `find` queries.  If you have no `find` in your keybinding/setting, this extension will use any selections in the file as the `find` queries.

If you have text like `someText\d+.ext\d`

and select it, then text like this will match and be selected and replaced if you have a `replace` field:

```plaintext
someText1.ext0
someText222.ext1
someText3333.ext2
```

```jsonc
{
  "key": "alt+e",
  "command": "findInCurrentFile",
  "args": {
    "isRegex": true,             // MUST have this for the selection(s) to be treated as a regex
    // "replace": "some replacement"
  }
},
```

You can even select 2 or more regex's in the file and have them all select any matches:

![regexFromText](https://github.com/ArturoDent/find-and-transform/assets/31813701/82378b38-29ce-4f66-ab8a-6d0068603780)

Is there something else you wanted to do not covered by the above?

**Comment by Haale** [comment]
> How do you want to use this exactly? In general, you can not use javascript to create a `find` query from code selected in a file (although that is an interesting idea), but you can use regex's in text as `find` queries. If you have no `find` in your keybinding/setting, this extension will use any selections in the file as the `find` queries.
> 
> If you have text like `someText\d+.ext\d`
> 
> and select it, then text like this will match and be selected and replaced if you have a `replace` field:
> 
> ```
> someText1.ext0
> someText222.ext1
> someText3333.ext2
> ```
> 
> ```js
> {
>   "key": "alt+e",
>   "command": "findInCurrentFile",
>   "args": {
>     "isRegex": true,             // MUST have this for the selection(s) to be treated as a regex
>     // "replace": "some replacement"
>   }
> },
> ```
> 
> You can even select 2 or more regex's in the file and have them all select any matches:
> 
> ![regexFromText](https://user-images.githubusercontent.com/31813701/257646164-82378b38-29ce-4f66-ab8a-6d0068603780.gif)
> 
> Is there something else you wanted to do not covered by the above?

Noted
