### ISSUE TITLE
${pathLikeVariable} slashes are escaped in "replace" argument of "runInSearchPanel" on MacOS

### ISSUE THREAD

**Issue by mlao-pdx** [ArturoDent/find-and-transform#22]
## Issue

The Replace argument escapes forward slashes for a `runInSearchPanel` command when using ${workspaceFolder}. ${pathSeparator} and other path-like variables behave similarly, while literal slashes are left alone.

## Sample keybinding

```jsonc
  {
    // Substitute placeholder with current workspaceFolder path
    "args": {
      "filesToInclude": "${workspaceFolder}", // .asciidoctorconfig.adoc", // Limit scope for safety
      "filesToExclude": "${workspaceFolder}", // Just to demonstrate issue
      "find": "${workspaceFolder}", // "◊Press_alt_p_to_fix◊", // Placeholder that leads user to here
      "isRegex": true,
      "matchCase": true, // Limit scope for safety
      "preserveCase": false, // Keep replace value as-is
      "replace": "${workspaceFolder}", // Slashes come through escaped
      "triggerReplaceAll": true, // Will still present confirmation dialog
      "triggerSearch": true // Required to triggerReplacAll
    },
    "command": "runInSearchPanel",
    "key": "alt+p"
  }
```

## Output for sample keybinding

The Replace field, and only the Replace field, has `\/` instead of a single `/`, as can be seen in this redacted screenshot:

<img width="454" alt="EscapingSlashesInReplace" src="https://github.com/ArturoDent/find-and-transform/assets/21014310/441cc16e-53b4-4e2e-a3a7-f73f41135d1e">

## System info
| Software | Version |
|----------|---------|
|Find and Transform| v4.8.2|
|VS Code| v1.81.1|
|MacOS| Ventura 13.4.1 (c)|

**Comment by ArturoDent** [comment]
Give v4.8.3 a try.  I reduced the instances of escaping for `replaces`.  Sometimes it is necessary within a variable resolution in a jsOperation, like 

```jsonc
      "replace": [
        "$${",
          "let re = '${selectedText}';",
          ......
        "}$$",
      ],
```

where the `${selectedText}` variable may contain forward slashes.

**Comment by ArturoDent** [comment]
By the way, this comment isn't really true:

```jsonc
"triggerSearch": true // Required to triggerReplacAll
```

as if you have ` "triggerReplaceAll": true,` then `"triggerSearch": true` will be automatically added.

That doesn't mean it isn't good practice to include both for clarity though.

**Comment by mlao-pdx** [comment]
> Give v4.8.3 a try. I reduced the instances of escaping for `replaces`. Sometimes it is necessary within a variable resolution in a jsOperation, like
> 
> ```js
>       "replace": [
>         "$${",
>           "let re = '${selectedText}';",
>           ......
>         "}$$",
>       ],
> ```
> 
> where the `${selectedText}` variable may contain forward slashes.

I expected it was related to things like group references in the Replace value and such.

I can confirm that 4.8.3 resolves my concerns, slashes are no longer escaped. Thank you for the swift response.
