### ISSUE TITLE
Compatibility with editor.codeActionsOnSave

### ISSUE THREAD

**Issue by mitechzone** [ArturoDent/find-and-transform#25]
I'm using the extension in `editor.codeActionsOnSave` to automate the LastUpdated change in XML files.

When I save the file, the extension is executed as expected, but the file is immediately marked as "dirty" again (with the dot in the tab). Because of this behavior, VS Code refuses to close the file tab.

Is it possible to prevent this behavior?

**Comment by ArturoDent** [comment]
I have seen this in the past but I thought it stopped happening.  And I can't reproduce it now. 

If it is still happening for you, can you show the settings you are using and some sample text for then to work on.

**Comment by ArturoDent** [comment]
Could you provide the setting or keybinding that you are using?  Thanks.

**Comment by mitechzone** [comment]
Certainly!

```
    "findInCurrentFile": {
        "updateLastModified": {
            "title": "Update LastModified Attribute",
            "find": "LastModified=\"(?!${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE}T${CURRENT_HOUR}:${CURRENT_MINUTE}:${CURRENT_SECOND}${CURRENT_TIMEZONE_OFFSET})[^\"]*\"",
            "replace": "LastModified=\"${CURRENT_YEAR}-${CURRENT_MONTH}-${CURRENT_DATE}T${CURRENT_HOUR}:${CURRENT_MINUTE}:${CURRENT_SECOND}${CURRENT_TIMEZONE_OFFSET}\"",
            "isRegex": true,
            "preserveSelections": true,
        },
    },
    "editor.codeActionsOnSave": [
        "source.updateLastModified",
    ],
```

**Comment by ArturoDent** [comment]
I can't replicate this yet.  What is your `"editor.formatOnSave"` setting?  Anything else running on a save?

**Comment by ArturoDent** [comment]
Give v5.3.0 a try, I believe your issue (and more codeAction-related issues) are fixed.  Mostly async issues with the `editBuilder` function.

![lastModifiedCodeAction](https://github.com/ArturoDent/find-and-transform/assets/31813701/3497baae-2931-491f-83ad-f7449327b779)

The below runs 2 codeActions from this extension and the first codeAction has a `"preCommands": "editor.action.formatDocument"`.

![formatCodeAction](https://github.com/ArturoDent/find-and-transform/assets/31813701/a87a3224-887e-4867-ac80-aa7f32e9e220)

**Comment by mitechzone** [comment]
Thank you!
