### ISSUE TITLE
Doing math on replacements return 'undefined'

### ISSUE THREAD

**Issue by Falcon5077** [ArturoDent/find-and-transform#27]
settings.json
<img width="550" alt="스크린샷 2024-03-17 오전 2 23 25" src="https://github.com/ArturoDent/find-and-transform/assets/32628758/216ec695-2a4d-4890-8631-5128e6226c71">

keybindings.json 
<img width="701" alt="스크린샷 2024-03-17 오전 2 23 39" src="https://github.com/ArturoDent/find-and-transform/assets/32628758/8894f8f8-058e-4832-9a8a-88e0db4b1033">

Every setting is perfect. And I pressed 'Alt + 1',
It works good 'Find' with regex

But return value is "undefined"
What's wrong my "replace" (Even I copied that from explaination)
I want actually just $$($1 + $2 + $3), and also return undefined

<img width="337" alt="스크린샷 2024-03-17 오전 2 26 30" src="https://github.com/ArturoDent/find-and-transform/assets/32628758/32b18541-51ef-4ae6-a2eb-6da55f2aa0ce">

I'm gonna die..💀 Please Help me

**Comment by ArturoDent** [comment]
Thanks for filing this issue.  I did some regular expression work in the last release and it screwed up the jsOperation functionality.

I just published v5.1.2 which should work fine.  Make sure you do not have v5.1.1.

Please let me know if it works for you now.  Thanks.

**Comment by Falcon5077** [comment]
Thank you!! It works perfectly.
I have an additional question. 

There are two situations, A+B-C and A-B+C. (operator's order)
I placed them in 'alt+1' and 'alt+2' each other, I want to combine them.

Calculating with 'replaces' can do it, but I think regex will not work about matching correct operator.

Is it possible?

**Comment by ArturoDent** [comment]
Not sure I completely follow.  Are ` A+B-C and A-B+C` what you need to match or are those the replacements you want to do?

```

```

**Comment by Falcon5077** [comment]
I think need to press another key to solve two case. But this is enough. Thank you!!
