### ISSUE TITLE
Global variable used in each replace

### ISSUE THREAD

**Issue by Bullfrog1234** [ArturoDent/find-and-transform#29]
Is there a way to set a variable as global for the execution of the replace scripts. 

This way a script can pass information from one replace to the next. 

For example, incrementing an integer to achieve this:

```js

// Before
const id = 1
const id = 1
const id = 1
const id = 1

// After
const id = 1
const id = 2
const id = 3
const id = 4

````

Would set a global variable that could be initialized as 1 then each replace it is incremented as one.

**Comment by ArturoDent** [comment]
`id` would be the global variable? You could find it with a regex and then `$1` or whichever capture group you used would always be `id`.

**Comment by ArturoDent** [comment]
Closing for lack of response.
