### ISSUE TITLE
Negative character class failing to find question mark

### ISSUE THREAD

**Issue by charliehamu** [ArturoDent/find-and-transform#30]
This code will not match the question mark character:
```
{ // in settings.json
  ...
  "findInCurrentFile": { 
    "questionable": {
      "find": "[^\\n]",
      "replace: "=",
      "isRegex": true,
    },
  ...
}
```
Input:
```
A simple test. Is this right? I think, indeed I know, not!
I'd pay $1 (or more) to lurn [sic] why. |\@#%^&*{}<>/~_-+=
```
Output:
```
============================?=============================
==========================================================
```
But it works find if placed in runInSearchPanel.

**Comment by ArturoDent** [comment]
I'm afraid the explanation is complex and has to do with escaping characters in settings - which is a pain.  This works (in both the Find and Search):

```jsonc
      "title": "myTitle Find",
      "find": "[^\n]",            //  note that there is no need for double-escaping here
      "replace": "=",
      "isRegex": true,
    }
```

In general, you do not have to double-escape the `\n` in a `find` value.  You will notice that you do NOT get any error squigglies if you do not double-escape so that usually indicates you are good without double-escaping.

Note that in the Find widget, `[^\\n]` would not do what you want at all.  

But there was a larger problem revealed by your issue which I believe I have fixed.

In order to be platform dependent, vscode replaces `\n` with `\r?\n`.  So this extension must do the same.  However, it shouldn't be done in a regex with `[\n in here somewhere]`, like your `[^\\n]`, as `[^\r?\n]` would be read by a regex engine to exclude the `?` character not as an optional indicator - just the way character classes like `[]` work.

SO I had to come up with a fancy regex which does replace `\n` with `\r?\n` everywhere but not in `[]`.  And `\\n` should work in a character class just like `\n`.

I uploaded a new version v5.2.0. Please update to that and let me know if the problem persists.

Thank you.

**Comment by charliehamu** [comment]
Huh. I was repeated writing patterns without double-escaping, and then needing to double-escape to make them work. I'll reread your notes about double-escaping and review where I thought I needed the double-escapes.

I'll download the updated extension tomorrow and check. Thanks for the quick update.

In the meanwhile, I had found a workaround using `.*\n` rather than `[^\n]*\n` that worked in my circumstance. I was glad not to be forced into `([\n]|\?)`.

**Comment by charliehamu** [comment]
I wonder if there is a "right" answers to making `[\n]` and `[^\n]` platform independent?

Neither `[\r\n]` nor `[^\r\n]` seem quite right, in that they give a lone `\r` special treatment.

Maybe that's okay. Didn't it used to be the case that `\n` was Un*x, `\r\n` was DOS, _and `\r` was Mac_?

**Comment by charliehamu** [comment]
Okay. Here's a question that I expect to be asking tomorrow. If I don't need to double-escape `[\n]` then surely I can't double-escape it, as `[\\n]` would then be interpreted as the character class consisting of `\` and `\n`. And if it isn't, why not? And how would I express the character class equivalent to `\\|n`?

**Comment by ArturoDent** [comment]
I removed transforming `\n` to `\r?\n` altogether inside those character classes `[....]`.  It isn't necessary there on any OS but is elsewhere.  So the extension will not create `[\r\n]` or `[^\r\n]` of its accord.

And I added a check for the EOL so it only makes the transform on CRLF systems (Windows) - when not in a character class.

> And how would I express the character class equivalent to \\|n?

  Try `[n\\]` (I haven't tried it though.)

> And \\n should work in a character class just like \n.

That I can't fully explain.  There are some complications when escaping things in settings and keybindings as one escape is typically removed simply on reading that setting, etc. before actually using it in some string which if read by another function may need to be escaped again.  But `\n` apparently gets special treatment by vscode.  For example, if you write `\n\s` in this extension's keybindings or settings you will get error squigglies for the `\s` only so you need to use `\n\\s`.  You DON'T need to use `\\n\\s`.  

I really don't know why that is other than to guess that there is specific code that handles any settings or keybindings looking for `\n` or `\\n`.  Like this code from src/vs/editor/common/core/textChange.ts

```js
function escapeNewLine(str: string): string {
  return (
    str
     .replace(/\n/g, '\\n')
     .replace(/\r/g, '\\r')
  );
}
```

Vscode is changing `\n` to `\\n` there.  And see https://github.com/microsoft/vscode/blob/85e9b0786cc505d85f326991227de364a5bd7293/src/vs/workbench/services/search/node/ripgrepTextSearchEngine.ts#L577 and lots more.

**Comment by charliehamu** [comment]
Thanks! I went to reproduce the problem this morning before updating the extension, but the extension had already auto-updated and the problem was gone.

I also noted that `[^\n]` was matching `\r`.

I speculate that '\n`, `\r', and `\t` don't need double-escaping because they resolve into characters that are allowed to be where the codes were placed and don't resolve further.

**Comment by charliehamu** [comment]
Adding here as it appears this might be a knock-on effect of the bug fix.

It looks like each highlighted replacement is one character earlier than it should be, cumulatively.

First highlight is one character too early; second highlight is two characters too early; etc.

**Comment by ArturoDent** [comment]
I made some more updates, closing as the original issue is resolved I believe.  Latest version is 5.2.3.

**Comment by charliehamu** [comment]
Yes. Original issue is resolved. I'll post again if there are any other
issues. Thanks!
