### ISSUE TITLE
Does `runInSearchPanel` supports math?

### ISSUE THREAD

**Issue by JohanMouchet** [ArturoDent/find-and-transform#4]
Thanks for this amazing tool.
I'm wondering if `runInSearchPanel` supports math?

Given the following `settings.json`:
```
"runInSearchPanel": {
  "myTitle": {
    "title": "myTitle",
    "find": "(\\d)",
    "replace": "$${{return $1 + 1}}$$",
    "isRegex": true,
    "triggerSearch": true,
    "triggerReplaceAll": true
  }
}
```

With the following file to go through:
```
1
2
3
```

The tool returns:
```
${return 1 + 1}$
${return 2 + 1}$
${return 3 + 1}$
```

When my expected result was:
```
2
3
4
```

Am I using the tool incorrectly?
Or, if `runInSearchPanel` doesn't support math, what would be the recommended way to go through many files in a single command?

Cheers

**Comment by ArturoDent** [comment]
`runInSearchPanel ` does not support javascript operations.  And you wouldn't have gotten intellisense supporting `${{...}}$`.

It isn't realistically possible right now.  There may be a proposed api that can do this in the future.

As of now, it would require this extension to open all files in the files to include and perform the operation on each.  The return value, the result of the math, would have to be calculated for each match in each file.  While that is theoretically possibly, the performance implications would be pretty bad.

I am keeping my eye on the proposed api in the meantime.

**Comment by ryanfitzer** [comment]
I've read through the docs, and also had a hard time figuring this out. It would be good to point that out in the "[Doing math on replacements](https://github.com/ArturoDent/find-and-transform/issues/4#doing-math-on-replacements)" section.

Does this also mean there is no other way to run math operations across multiple files? Is the only option in the currently open file?
