### ISSUE TITLE
Error: ENOENT: no such file or directory, access 'c:\Users\Mark\find-and-transform'

### ISSUE THREAD

**Issue by boompsy** [ArturoDent/find-and-transform#5]
I just upgraded VS Code to 1.67.1 and suddenly my extensions stopped working. After I disabled the Find and Transform extension and reloaded VS Code, things started working again.

I looked at the Log (Window) Output window and noticed the following entry, which led me to identifying the symptom:
Error: ENOENT: no such file or directory, access 'c:\Users\Mark\find-and-transform'

**Comment by ArturoDent** [comment]
Thanks for the issue.  I think I fixed it in v2.4.6.  Some path information was automatically added to the `package.json` long ago by vscode.  I don't know why, or why it didn't break things until now?

Please install v2.4.6 and let me know if it works for you.

Thanks.

**Comment by boompsy** [comment]
Wow! Thanks for the super quick response! Fixed now.
